# care_management/care_management/services/custom_plan_sync_engine.py

import frappe
from frappe import _
from frappe.utils import getdate, today, now_datetime


class CustomPlanSyncEngine:
    """
    Synchronizes Custom Care Plan activities directly into the native
    Support Task and Support Task Schedule Rule child table schema.
    """

    SOURCE_DOCTYPE = "Custom Care Plan"

    CATEGORY_FALLBACKS = (
        "Shift Task",
        "Community Access",
        "Personal Care",
    )

    DAY_MAP = {
        "mon": "monday",
        "monday": "monday",
        "tue": "tuesday",
        "tuesday": "tuesday",
        "wed": "wednesday",
        "wednesday": "wednesday",
        "thu": "thursday",
        "thursday": "thursday",
        "fri": "friday",
        "friday": "friday",
        "sat": "saturday",
        "saturday": "saturday",
        "sun": "sunday",
        "sunday": "sunday",
    }

    PRIORITY_MAP = {
        "Low": "Optional",
        "Medium": "Mandatory",
        "High": "Clinical",
        "Urgent": "Critical",
    }

    def __init__(self, plan_doc):
        self.plan = plan_doc
        self.source_doctype = self.SOURCE_DOCTYPE
        self.source_docname = plan_doc.name

    # -------------------------------------------------------------------------
    # PUBLIC API
    # -------------------------------------------------------------------------

    def sync(self):
        """Synchronize active activities into Support Tasks."""
        if self.plan.status != "Active":
            return

        if not self.plan.activities:
            self._deactivate_all_tasks(reason=_("No activities in Custom Care Plan."))
            return

        active_row_ids = set()

        for activity in self.plan.activities:
            if not self._is_activity_active(activity):
                continue

            active_row_ids.add(activity.name)
            task = self._upsert_support_task(activity)

            if getattr(activity, "source_task_ref", None) != task.name:
                frappe.db.set_value(
                    "Custom Care Plan Activity",
                    activity.name,
                    "source_task_ref",
                    task.name,
                    update_modified=False,
                )
                activity.source_task_ref = task.name

        self._sync_stale_tasks(active_row_ids)

    def deactivate_all_schedules(self, reason=None):
        """
        Deactivates all Support Tasks generated by this plan (sets status='Paused' / 'Archived')
        and cancels only future Pending execution instances.
        """
        tasks = frappe.get_all(
            "Support Task",
            filters={
                "source_doctype": self.source_doctype,
                "source_docname": self.source_docname,
            },
            pluck="name",
        )

        if not tasks:
            return

        for task_name in tasks:
            frappe.db.set_value(
                "Support Task",
                task_name,
                "status",
                "Paused",
                update_modified=False,
            )

        self._cancel_future_pending_instances(
            tasks,
            reason or _("Custom Care Plan deactivated"),
        )

    # -------------------------------------------------------------------------
    # SUPPORT TASK BUILDER
    # -------------------------------------------------------------------------

    def _upsert_support_task(self, activity):
        filters = {
            "source_doctype": self.source_doctype,
            "source_docname": self.source_docname,
            "source_row_id": activity.name,
        }

        task_name = frappe.db.get_value("Support Task", filters, "name")

        if task_name:
            task = frappe.get_doc("Support Task", task_name)
        else:
            task = frappe.new_doc("Support Task")
            task.source_doctype = self.source_doctype
            task.source_docname = self.source_docname
            task.source_row_id = activity.name
            task.auto_generated = 1

        task_meta = task.meta

        # Link Support Plan
        task.support_plan = self._resolve_support_plan_reference(task_meta)

        # Status: MUST BE 'Active'
        task.status = "Active"

        # Resolve Category safely
        resolved_category = self._resolve_task_category(activity.activity_category, task_meta)
        task.task_category = resolved_category

        # Formatted Display Name
        category_tag = f"[{activity.activity_category}]" if activity.activity_category != resolved_category else ""
        task.task_name = f"{category_tag} {activity.activity_name}".strip() if category_tag else activity.activity_name

        # Priority & Instructions
        task.clinical_priority = self.PRIORITY_MAP.get(activity.priority, "Mandatory")
        task.description = activity.instructions or ""
        task.staff_count_required = activity.staff_count_required or 1
        task.estimated_duration_mins = activity.expected_duration_minutes or 30

        # Audit user
        if not task.created_by_user:
            task.created_by_user = frappe.session.user

        # Sync Embedded Schedule Rule Child Table
        self._sync_embedded_schedule_rule(task, activity)

        task.flags.ignore_permissions = True
        task.save()
        return task

    # -------------------------------------------------------------------------
    # SCHEDULE RULE CHILD TABLE HANDLER
    # -------------------------------------------------------------------------

    def _sync_embedded_schedule_rule(self, task, activity):
        """Builds the exact Support Task Schedule Rule child row."""
        rule_row = None
        if task.schedule_rules:
            rule_row = task.schedule_rules[0]
        else:
            rule_row = task.append("schedule_rules", {})

        # Schedule timing
        rule_row.scheduled_time = activity.scheduled_time
        rule_row.start_date = max(getdate(self.plan.start_date), getdate(today()))
        rule_row.end_date = self.plan.end_date

        # Reset all day checkboxes
        weekdays = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
        for d in weekdays:
            setattr(rule_row, d, 0)

        # Map Recurrence Type & Checkboxes correctly
        freq = (activity.frequency or "").strip()

        if freq == "Daily":
            rule_row.recurrence_type = "Daily"
            for d in weekdays:
                setattr(rule_row, d, 1)

        elif freq in ["Weekly", "Specific Days"]:
            rule_row.recurrence_type = "Selected Days"  # Matches schema options
            days_checked = self._parse_selected_days(activity.days_of_week)
            for d in days_checked:
                setattr(rule_row, d, 1)

        elif freq == "Monthly":
            rule_row.recurrence_type = "Monthly"

        else:
            rule_row.recurrence_type = "Daily"

    def _parse_selected_days(self, raw_days):
        """Converts string like 'Mon, Wed' or 'Monday' to lowercase field names."""
        if not raw_days:
            return []

        tokens = [d.strip().lower() for d in str(raw_days).replace(";", ",").split(",") if d.strip()]
        selected = []
        for token in tokens:
            if token in self.DAY_MAP:
                col_name = self.DAY_MAP[token]
                if col_name not in selected:
                    selected.append(col_name)
        return selected

    # -------------------------------------------------------------------------
    # LOOKUPS & SUPPORT PLAN
    # -------------------------------------------------------------------------

    def _resolve_support_plan_reference(self, task_meta):
        field = task_meta.get_field("support_plan")
        options = (getattr(field, "options", None) or "").strip()

        if not options or not frappe.db.exists("DocType", options):
            return self.plan.name

        target_meta = frappe.get_meta(options)
        p_field = "participant_profile" if target_meta.has_field("participant_profile") else "participant"

        if target_meta.has_field(p_field):
            existing = frappe.db.get_value(
                options,
                {p_field: self.plan.participant},
                "name",
            )
            if existing:
                return existing

        return self.plan.name

    def _resolve_task_category(self, activity_category, task_meta):
        field = task_meta.get_field("task_category")
        raw_options = getattr(field, "options", "") or ""
        valid_options = [opt.strip() for opt in raw_options.split("\n") if opt.strip()]

        if activity_category in valid_options:
            return activity_category

        for fallback in self.CATEGORY_FALLBACKS:
            if fallback in valid_options:
                return fallback

        return valid_options[0] if valid_options else "Shift Task"

    # -------------------------------------------------------------------------
    # STALE & DEACTIVATION
    # -------------------------------------------------------------------------

    def _sync_stale_tasks(self, active_row_ids):
        existing_tasks = frappe.get_all(
            "Support Task",
            filters={
                "source_doctype": self.source_doctype,
                "source_docname": self.source_docname,
            },
            fields=["name", "source_row_id"],
        )

        for task_info in existing_tasks:
            if task_info.source_row_id in active_row_ids:
                continue

            # Pause stale task
            frappe.db.set_value(
                "Support Task",
                task_info.name,
                "status",
                "Paused",
                update_modified=False,
            )

            self._cancel_future_pending_instances(
                [task_info.name],
                _("Activity removed from Custom Care Plan"),
            )

    def _deactivate_all_tasks(self, reason):
        tasks = frappe.get_all(
            "Support Task",
            filters={
                "source_doctype": self.source_doctype,
                "source_docname": self.source_docname,
            },
            pluck="name",
        )

        for task_name in tasks:
            frappe.db.set_value(
                "Support Task",
                task_name,
                "status",
                "Paused",
                update_modified=False,
            )

        self._cancel_future_pending_instances(tasks, reason)

    def _cancel_future_pending_instances(self, task_names, reason):
        if not task_names or not frappe.db.exists("DocType", "Support Task Execution Instance"):
            return

        execution_meta = frappe.get_meta("Support Task Execution Instance")
        if not execution_meta.has_field("support_task"):
            return

        date_field = None
        for candidate in ("scheduled_date", "scheduled_datetime", "execution_date"):
            if execution_meta.has_field(candidate):
                date_field = candidate
                break

        filters = {
            "support_task": ["in", task_names],
            "status": ["in", ["Draft", "Pending", "Scheduled"]],
        }
        if date_field:
            filters[date_field] = [">=", today()]

        pending = frappe.get_all(
            "Support Task Execution Instance",
            filters=filters,
            fields=["name"],
        )

        for item in pending:
            values = {"status": "Cancelled"}
            if execution_meta.has_field("cancellation_reason"):
                values["cancellation_reason"] = reason
            if execution_meta.has_field("cancelled_at"):
                values["cancelled_at"] = now_datetime()

            frappe.db.set_value(
                "Support Task Execution Instance",
                item.name,
                values,
                update_modified=False,
            )

    @staticmethod
    def _is_activity_active(activity):
        return bool(getattr(activity, "is_active", 1))